### ISSUE TITLE
Design the quiz

### ISSUE THREAD

**Issue by Protohedgehog** [OpenScienceMOOC/Module-1-Open-Principles#19]
Will have to design a quiz for this, similar to Module 5: https://github.com/OpenScienceMOOC/Module-5-Open-Research-Software-and-Open-Source/blob/master/content_development/04-quizzes.md

**Comment by Protohedgehog** [comment]
https://github.com/OpenScienceMOOC/Module-1-Open-Principles/blob/master/content_development/script_intro.md

**Comment by johav** [comment]
Just drafting a few ideas for quiz questions:

**What is Open Science?**
- [X] All scientific research, data and dissemination is accessible to all levels of society.
- [ ] Research institutes provide an open-door day at least once a year.
- [ ] Any research outside the laboratory or an office, in other words the same as 'field research'. 

**Open Science implies the same for all disciplines. true or false?**
- [ ] True
- [X] False

Different research disciplines approach Open Science differently and develop their own standards. This is mostly due to the variety of methodologies and specific community standards that already exist in each discipline (historically grown).

**Besides Openness, what are the inherent values in Open Science?**
- [X] diversity, inclusivity, fairness, equity, social behaviour, accountability, ethics and responsibility
- [ ] fun, action, humour
- [ ] stress resistance, patience, durability, high work capacity

** Open Science only matters to scientists in underprivileged regions of the world (or a nation)
- [ ] True
- [X] False

** Open Science is a new invention to liberate research output from corporate publishers and their paywalls
- [ ] True
- [X] False

The debate about Open Science in recent scientific literature picked up as early as ... (1970?). The term itself was first used by... in ... if it wasn't for open knowledge exchange between scientists and the public and amongst scientists across disciplines many achievements of the past would have taken much more time. (famous example?)

** Implementing Open Science practices adds more steps to the research cycle but saves a lot of time, resources and effort.
- [X] True
- [ ] False

** which of the following is NOT a category of Open Science?
- [ ] Open Access
- [ ] Open Peer Review
- [X] Open Windows
- [ ] Open Source (Hard & Software)
- [ ] Open Methodology
- [ ] Preregistration

**Comment by Protohedgehog** [comment]
Note that @johav seems to have made some great progress on this so far!

**Comment by ivogrigorov** [comment]
I like!

We need to load the answers with key references that dispel myths, and reinforce measurable benefits.

As this is going to be our canvas to nail down some principles, I think we need 1-2 quiz questions to re-iterate speeding the discovery process, & solutions to societal problems & UN SDGs.

Suggestions:

Q: Open Science is just another term for digital “house cleaning” exercise in the lab.

True:
False: tick

A: Just like sharing ideas at a conference can cross-fertilise ideas, boost trans-disciplinary research and spin off unexpected collaborations, so access to all parts of the research lifecycle can exponentially add to re-use of your outputs. In a digital age, Open Science applies at all steps of the Research Lifecycle speeds up the discovery process (cf Michael Nielsen) allows your research output to passively promote your work and pave the way for collaborations beyond your discipline, even while you sleep.

Q: Open Science has little relevance to societal challenges.

True:
False: tick
A: Access to research outputs is an issues for researchers (need a good citation), developing world (need a good citation), as well as industry (report by RIN 2011). Access to research outputs, and speeding up the discovery process on issues of importance to time-sensitive UN Sustainable Development Goals (e.g. climate, poverty, health etc) is key in achieving SDGs.



Sent from my iPhone

On 22 Jan 2019, at 17.52, Jon Tennant <notifications@github.com<mailto:notifications@github.com>> wrote:


Note that @johav<https://github.com/johav> seems to have made some great progress on this so far!

**Comment by Protohedgehog** [comment]
These look awesome, @ivogrigorov! Would you like to integrate them into the quiz file (see comments above) for safekeeping? :)

**Comment by Protohedgehog** [comment]
@ivogrigorov I have started adding the quiz in here: https://eliademy.com/app/a/quizzes/836269

I'm gonna ping you an email invite, and if I upgrade you then you could add these in? :)

**Comment by ivogrigorov** [comment]
@Protohedgehog hey dude, invitation came through, had a test ride, but no editing rights. Am I being dopy?!

**Comment by Protohedgehog** [comment]
Check again! Just needed to upgrade you :)

**Comment by ivogrigorov** [comment]
I know it must be tempting, but dont give up on me ... still no access to quiz rights, now I am just enroled and can edit course description (?!) cant sit quiz

**Comment by Protohedgehog** [comment]
Oops, sorry @ivogrigorov, that will teach me for trying to do this on mobile. You should have admin privileges now! :)

**Comment by Protohedgehog** [comment]
Last chance to check the quiz content!
